variable "region" {}
variable "subnetA-arn" {}
variable "subnetA-arn" {}
variable "rds-password" {}
variable "rds-endpoint" {}
variable "vpc-id" {}
variable "access-key-id" {}
variable "secret-key" {}
variable "subnetA-id" {}
variable "subnetB-id" {}